### ISSUE TITLE
用户bot (user-bot / self-bot) 无法获取消息的content

### ISSUE THREAD

**Issue by An9el0baby** [Snapmali/discord-monitor#10]
discord 好像更新了用户的token
无法获取其他人发送的mesage的content
请问有方法解决吗？

**Comment by Snapmali** [comment]
应该是4月30日discord对api做了某种修改所致，而目前discord.py库已不再为selfbot的问题提供维护与帮助，甚至将在未来的v2.0版本直接移除对selfbot的支持，相关讨论可参见https://github.com/Rapptz/discord.py/issues/6839 
而我这里只能考虑针对selfbot的情形迁移依赖库，目前正在考虑的选项为[Discord-S.C.U.M](https://github.com/Merubokkusu/Discord-S.C.U.M)
由于本人的精力及能力所限，不排除脚本最终直接放弃对用户bot的支持的可能性，敬请谅解

**Comment by An9el0baby** [comment]
好的 感谢您及时回答！

**Comment by tom-snow** [comment]
https://github.com/Sopur/Discord-user-bots

**Comment by tom-snow** [comment]
https://github.com/dolfies/discord.py-self

感觉这个好像可以,不过本项目不能简单通过修改 discord.py 依赖库为 discord.py-self 来用

**Comment by luoyeETH** [comment]
> https://github.com/dolfies/discord.py-self
> 
> 感觉这个好像可以,不过本项目不能简单通过修改 discord.py 依赖库为 discord.py-self 来用

这个确实可以，改为`discord.py-self`后，修改一下就可以运行用户bot了

**Comment by costard06** [comment]
> > https://github.com/dolfies/discord.py-self
> > 感觉这个好像可以,不过本项目不能简单通过修改 discord.py 依赖库为 discord.py-self 来用
> 
> 这个确实可以，改为`discord.py-self`后，修改一下就可以运行用户bot了

请问luoye大佬 依赖库改为discord.py-self后，需要修改哪个地方的代码才能实现on_message获取content？请指教🙏

**Comment by luoyeETH** [comment]
> > > https://github.com/dolfies/discord.py-self
> > > 感觉这个好像可以,不过本项目不能简单通过修改 discord.py 依赖库为 discord.py-self 来用
> > 
> > 
> > 这个确实可以，改为`discord.py-self`后，修改一下就可以运行用户bot了
> 
> 请问luoye大佬 依赖库改为discord.py-self后，需要修改哪个地方的代码才能实现on_message获取content？请指教🙏

作者原代码中既支持bot也支持self-bot，修改后需要将`DiscordMonitor.py`中  
```
dc.run(config["token"], bot=config["bot"])
```  
修改为  
```
dc.run(config["token"])
```
之后可能运行时还会有字符串拼接的报错，再自行修改一下就行。  
```
log_text = '%s: ID: %d. Username: %s. Server: %s. Channel: %s. Content: %s%s' % \
                   (status, message.author.id,
                    message.author.name + '#' + message.author.discriminator,
                    message.guild.name, message.channel.name, message.content, attachment_log)
```
可能是上面这部分代码，记不太清了

**Comment by Snapmali** [comment]
已经引入discord.py-self解决问题，请详阅readme中[外部依赖库](https://github.com/Snapmali/discord-monitor#%E5%A4%96%E9%83%A8%E4%BE%9D%E8%B5%96%E5%BA%93)进行处理。

**Comment by ferrenlove** [comment]
感谢美女、帅哥作者
