### ISSUE TITLE
推送消息中的附件未包含Embed中的图片

### ISSUE THREAD

**Issue by 1771269478** [Snapmali/discord-monitor#12]
环境信息

go-cqhttp最新版本:

目前我使用了免费版..
image
![image](https://user-images.githubusercontent.com/102167146/188508630-3a1e0714-163d-47a0-83b0-59644e77b282.png)

和
image
![image](https://user-images.githubusercontent.com/102167146/188508656-f0754875-4e26-4d46-92a1-441c12116e81.png)

目前使用的 插眼,并转发到QQ群..
一切都很好.但是在转发图片的时候出现了问题.
我发现当别人发出的图片都是 https://cdn.discordapp.com/ 开头的时候..软件不会识别到有图片.字符段返回none
我自己测试的时候,用网页端发出的图片.全部可以识别并被下载和转发
7)HWZR86D_$OUM1$A`$@T7O
![image](https://user-images.githubusercontent.com/102167146/188508681-0e50a049-3eae-409a-b915-c27b0467bf44.png)

请问怎么可以解决 无法转发图片的问题.

另外如果做一个 discord 转发到 discord 的软件 1000人民币的预算可以做吗.盼复谢谢

微信电话 13962164888

需要添加的功能内容

**Comment by Snapmali** [comment]
我没太看懂……只发图片不发文字消息的话正文就是显示None，你发的这张图一切都是正常的，我这边自行测试也是正常。
请详细描述一下如何复现错误。

**Comment by 1771269478** [comment]
好的稍等..不好意思我很业余 我马上描述一下

**Comment by Snapmali** [comment]
如果你是指只转发链接不加载图片，在QQ消息中显示discord消息图片功能需通过cqhttp应用连接至discord CDN服务器实现，如有必要请在cqhttp应用的配置文件中添加代理设置。

**Comment by 1771269478** [comment]
![image](https://user-images.githubusercontent.com/102167146/188639561-1cc471a0-cc76-4ffe-8e57-6527a2500e84.png)
我加入了一个付费社区...https://discord.com/channels/1004707886657699901/1004720271409807400
他里面的消息都是机器人从别的付费社区转发来的.
![image](https://user-images.githubusercontent.com/102167146/188639792-3dce8c83-4085-4719-94c7-0ac679cf1c84.png)
然后每个频道里的机器人都是不同的ID
![image](https://user-images.githubusercontent.com/102167146/188639977-a0fa459c-1a85-4a9d-8631-0137111d1872.png)
比如这个频道里.别人在聊天,他用机器人把别人的聊天记录爬过来
然后我发现 同一个频道里的机器人ID 是相同的

现在我把无法转发图片的情况我截图上来.
比如这个 今天20:40分的消息
![image](https://user-images.githubusercontent.com/102167146/188640788-454a651b-467c-4338-83f9-33bdd273eaa5.png)

![image](https://user-images.githubusercontent.com/102167146/188640678-ade91c1a-a18d-4247-a14f-3814dabe91d9.png)


我CQHTTP里面有添加代理设置.
![image](https://user-images.githubusercontent.com/102167146/188640975-aa7f9500-a0f2-4039-b14b-4d7d7feaf775.png)

然后什么时候会转发截图呢..我来截图 不是机器人发帖的时候.他就转发

**Comment by 1771269478** [comment]
![image](https://user-images.githubusercontent.com/102167146/188641425-c4ba587f-8015-465a-a053-cfc01762838c.png)
这是我在discord里发的

下面是我QQ里机器人发的
![image](https://user-images.githubusercontent.com/102167146/188641539-26e063f2-4ee3-4ca4-ba0d-f758d52af615.png)
![image](https://user-images.githubusercontent.com/102167146/188641559-04c62d18-1eda-4a30-b965-bc55da19c059.png)

**Comment by 1771269478** [comment]
请问  作者大佬..可以帮我做成  discord消息通过用户插眼.转发到我自己的discord频道里吗
这点预算够吗

**Comment by Snapmali** [comment]
问题已修复
