### ISSUE TITLE
关注的别的频道的消息无法被监听。

### ISSUE THREAD

**Issue by mikuyourworld** [Snapmali/discord-monitor#13]
设置好监听以后。自己发的测试消息可以被正常监听到。
但是利用discord的关注功能，转发到被监听频道的别的频道的消息无法被监听。

**Comment by Snapmali** [comment]
通知频道关注发布的功能本质是由webhook实现，需要你把对应webhook的ID添加至配置文件的监听用户列表。
![image](https://user-images.githubusercontent.com/34858368/194710553-8e89240f-114d-4c5a-af6f-13b4bc1dae61.png)

**Comment by mikuyourworld** [comment]
不好意思，第一次用discord的bot不太理解。问得可能有点儿多。
webhook是我自己服务器的webhook么？我自己服务器的webhook已经打开了。
对应webhook的ID是指哪一个呢？比如我的服务器频道是B。我关注了别的服务器的A频道，转发A的消息到我的频道B。
那这个ID是指A的ID还是B的ID呢？
还是说设置的我饿的webhook URL的连接里的那一串类似ID的数字呢？
还有一个问题是监听用户列表只是message_monitor下的监听用户么？

**Comment by Snapmali** [comment]
1. 是指B中负责转发消息的那个bot的ID，右键点那个bot的头像选复制ID就行。
2. 对，是message_monitor里的。

**Comment by mikuyourworld** [comment]
谢谢。
不过第一个ID还是没太对。我把几个id都添加了还是不行。
而且，还是没太理解。
【我的服务器B中负责转发消息的那个bot是什么。】
如果是使用discord的频道关注功能把某个频道的消息转发到自己的频道的话，
所有消息的发送者都是关注的那个频道的名字。
我复制了这个发送者的id（和原频道的id不一样的一个ID）添加到message_monitor的user id里了依然没有监听到。

**Comment by mikuyourworld** [comment]
根据别人的思路绕个圈子解决了。
再开了一个脚本，让机器人自己转发一次这个嵌套消息，就变成普通消息了。
然后就可以监听到了。

**Comment by Snapmali** [comment]
我这边测试对于关注功能发布的消息是可以转发的：
1. A服务器中的公告频道新发送了一条消息，并对关注者发布
![image](https://user-images.githubusercontent.com/34858368/194758440-84f1b3ba-8be2-43c1-a899-1aeb2f422e21.png)

2. B服务器的C频道关注了A服务器的公告频道，此时C频道接收到了由D转发的A服务器中的公告
![image](https://user-images.githubusercontent.com/34858368/194758651-a60cdddf-4086-4d5c-b5f3-2ac816317977.png)

3. 为了让脚本监听到该条消息，需要在配置文件中设置监听频道C及“用户”D
![image](https://user-images.githubusercontent.com/34858368/194758669-03d4dfe7-65b8-4fce-8941-73ac11ec5643.png)
![image](https://user-images.githubusercontent.com/34858368/194758643-500e1897-31b5-465b-95a0-31e59b034092.png)
![image](https://user-images.githubusercontent.com/34858368/194758887-67e4f8d1-b06b-4262-b98e-7605f7d629bb.png)

**Comment by mikuyourworld** [comment]
好详细！非常感谢！我再试试。
