### ISSUE TITLE
登录上去了，但是无法转发

### ISSUE THREAD

**Issue by xiaobaozi233** [Snapmali/discord-monitor#2]
Ignoring exception in on_message
Traceback (most recent call last):
  File "site-packages\discord\client.py", line 312, in _run_event
  File "DiscordMonitor.py", line 273, in on_message
  File "DiscordMonitor.py", line 143, in process_message
  File "DiscordMonitor.py", line 423, in push_message
TypeError: 'int' object is not subscriptable

**Comment by Snapmali** [comment]
请检查一下你的config.json中"push"的值的格式，具体格式如下：
```
"push": {
        //推送的QQ用户或群聊，为嵌套列表。底层列表第一个值为QQ号或群号；
        //第二个值为布尔型，表示是否推送消息动态；第三个值为布尔型，表示是否推送用户动态
        "QQ_group": [[1234567890, true, false], [9876543210, true, true]],
        "QQ_user": [[1234567890, true, false], [9876543210, true, true]]
    }
```

**Comment by xiaobaozi233** [comment]
谢谢，解决了。
但是推送到酷Q好像有点问题。
提示如下：
[ERROR][2020/07/30 16:58:51][Push] Failed to send message to group 1130209910. R
esponse:401. Message:

**Comment by Snapmali** [comment]
看coolq-http-api的文档的话401响应应该是请求时未提供access token，这个脚本在请求时是不提供access token的，请问你的coolq-http-api除了响应这个脚本之外还有其他用途吗？没有的话可以在coolq-http-api的配置文件中将access_token项设为空，即"access_token": ""
详见[https://cqhttp.cc/docs/4.15/#/Configuration?id=%E5%87%A0%E7%A7%8D%E5%85%B8%E5%9E%8B%E7%9A%84%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%AE%89%E6%8E%92%E6%96%B9%E5%BC%8F](url)

**Comment by xiaobaozi233** [comment]
好了解决了，谢谢。
另外我想要转发某个频道的所有消息到QQ或者群，这个可以实现吗？目前好像只能解决监视某个特定的人。
QQ和QQ群好像都要填写才能转发，QQ或者群二选一需要怎么更改配置文件啊？

**Comment by Snapmali** [comment]
这个脚本的目的就是监视特定个人的消息，如果你有python基础的话，可以尝试修改DiscordMonitor.py的以下行数，我没有测试过，注意缩进：
85行
```
if server in self.monitoring_server or True in self.monitoring_server:
```
103行
```
toast_title = '%s %s' % (message.author.name, status)
```
135行
```
(message.author.name,
```
156行
```
toast_title = '%s %s' % (user.name, status)
```
166行
```
(user.name,
```
另外，如果不想推送私聊或者群聊的话可以在json里留空。例如：
```
"push": {
        "QQ_group": [[123456789, true, true]],
        "QQ_user": []
    }
```

**Comment by xiaobaozi233** [comment]
测试好像成功了，但是只能监控一个服务器的所有频道，能否指定指定其中的部分频道进行监控呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snapmali/discord-monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 下午5:44
收件人:&nbsp;"Snapmali/discord-monitor"<discord-monitor@noreply.github.com&gt;;
抄送:&nbsp;"xiaobaozi"<xiaobaozi@miku.tw&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snapmali/discord-monitor] 登录上去了，但是无法转发 (#2)





 
这个脚本的目的就是监视特定个人的消息，如果你有python基础的话，可以修改DiscordMonitor.py的以下行数，注意缩进：
 85行
 if server in self.monitoring_server or True in self.monitoring_server:  
103行
 toast_title = '%s %s' % (message.author.name, status)  
135行
 (message.author.name,  
156行
 toast_title = '%s %s' % (message.author.name, status)  
166行
 (message.author.name,  
另外，如果不想推送私聊或者群聊的话可以在json里留空。例如：
 "push": {         "QQ_group": [[123456789, true, true]],         "QQ_user": []     }

**Comment by Snapmali** [comment]
最新的commit和release实现了这个功能，可以更新一下，注意config.json的格式更新

**Comment by xiaobaozi233** [comment]
十分感谢，帮了大忙了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snapmali/discord-monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上10:11
收件人:&nbsp;"Snapmali/discord-monitor"<discord-monitor@noreply.github.com&gt;;
抄送:&nbsp;"xiaobaozi"<xiaobaozi@miku.tw&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snapmali/discord-monitor] 登录上去了，但是无法转发 (#2)





 
最新的commit和release实现了这个功能，可以更新一下，注意config.json的格式更新
