### ISSUE TITLE
掉线无法自动重连的问题

### ISSUE THREAD

**Issue by xiaobaozi233** [Snapmali/discord-monitor#4]
换了个VPS解决了

_Originally posted by @xiaobaozi233 in https://github.com/Snapmali/discord-monitor/issues/3#issuecomment-667238192_

还是不行。。。网络应该没问题，就是掉线后看到连接了两次就卡主了一样没有反应了。

**Comment by Snapmali** [comment]
这个问题我这里也出现过，但情况较为复杂：比如我使用中国移动流量手机热点和移动宽带WiFi，用脚本连接Clash同一节点代理的情况下，移动流量会出现脚本启动几分钟后断连无法重连，且重启脚本后无法登录的问题，而移动宽带不会出现此问题，即使断连后也能及时重连。而在log中未发现有用信息。
即使不使用本脚本，直接运行discord.py文档提供的示例程序亦是此情况。你也可以参考此代码自行测试：
```
import discord

client = discord.Client(proxy='your proxy URL')

@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))

@client.event
async def on_connect():
    print('Connected!')

@client.event
async def on_disconnect():
    print('Disconnected...')

@client.event
async def on_message(message):
    print(message)

print("Logging in...")
client.run('your token', bot=False)
```
考虑应是网络问题，或者是discord.py依赖库的问题。很遗憾我这里暂时不能给出有效解决方案。建议更换脚本部署网络，如果有可用境外VPS的话，也可以考虑参考Linux部署方法将脚本部署在VPS上。

**Comment by xiaobaozi233** [comment]
我买的阿里云新加坡Orz也这样，自闭了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snapmali/discord-monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 中午1:14
收件人:&nbsp;"Snapmali/discord-monitor"<discord-monitor@noreply.github.com&gt;;
抄送:&nbsp;"xiaobaozi"<xiaobaozi@miku.tw&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Snapmali/discord-monitor] 换了个VPS解决了 (#4)





 
这个问题我这里也出现过，但情况较为复杂：比如我使用中国移动流量手机热点和移动宽带WiFi，用脚本连接Clash同一节点代理的情况下，移动流量会出现脚本启动几分钟后断连无法重连，且重启脚本后无法登录的问题，而移动宽带不会出现此问题，即使断连后也能及时重连。而在log中未发现有用信息。
 即使不使用本脚本，直接运行discord.py文档提供的示例程序亦是此情况。你也可以参考此代码自行测试：
 import discord client = discord.Client(proxy='your proxy URL') @client.event async def on_ready():     print('We have logged in as {0.user}'.format(client)) @client.event async def on_connect():     print('Connected!') @client.event async def on_disconnect():     print('Disconnected...') @client.event async def on_message(message):     if message.author == client.user:         return     if message.content.startswith('$hello'):         await message.channel.send('Hello!') print("Logging in...") client.run('your token', bot=False)  
考虑应是网络问题，或者是discord.py依赖库的问题。很遗憾我这里暂时不能给出有效解决方案。建议更换脚本部署网络，如果有可用境外VPS的话，也可以考虑参考Linux部署方法将脚本部署在VPS上。

**Comment by Snapmali** [comment]
参考了discord.py库中的如下issue：
[#4204 Switching Websockets library to support proxy scenarios](https://github.com/Rapptz/discord.py/issues/4204)
问题有可能出现在Websockets库不支持代理连接上。实际在debug级log中也确有发现断线可能为websocket所致：
```
2020-08-01 23:29:31,899:INFO:discord.gateway: Websocket closed with 1006 (), attempting a reconnect.
```
遵循issue中的建议，我在windows下使用proxifier对该脚本程序进行代理转发，表现良好：在测试的过程中，直接在config.json中定义代理地址后运行的脚本会出现disconnect现象，而由proxifier进行转发的脚本除网络波动外未出现断连。

若尝试此方法，建议将config.json中的"proxy"值留空，此外proxifier的使用方法可参考[此博客](https://blog.csdn.net/Amdy_amdy/article/details/84585063)，其中第四步是允许直连到代理服务器，防止造成循环代理错误，若不打算利用proxifier对所有程序进行全局代理可忽略。

**Comment by xiaobaozi233** [comment]
应该不是了，我把服务器换到了伦敦也有相同的问题。只是频率低了很多，估计只能设置一下定时重启才行了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snapmali/discord-monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 晚上11:58
收件人:&nbsp;"Snapmali/discord-monitor"<discord-monitor@noreply.github.com&gt;;
抄送:&nbsp;"xiaobaozi"<xiaobaozi@miku.tw&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Snapmali/discord-monitor] 掉线无法自动重连的问题 (#4)





 
参考了discord.py库中的如下issue：
 #4204 Switching Websockets library to support proxy scenarios
 问题有可能出现在Websockets库不支持代理连接上。实际在debug级log中也确有发现断线可能为websocket所致：
 2020-08-01 23:29:31,899:INFO:discord.gateway: Websocket closed with 1006 (), attempting a reconnect.  
遵循issue中的建议，我在windows下使用proxifier对该脚本程序进行代理转发，表现良好：在测试的过程中，直接在config.json中定义代理地址后运行的脚本会出现disconnect现象，而由proxifier进行转发的脚本除网络波动外未出现断连。
 
若尝试此方法，建议将config.json中的"proxy"值留空，此外proxifier的使用方法可参考此博客，其中第四步是允许直连到代理服务器，防止造成循环代理错误，若不打算利用proxifier对所有程序进行全局代理可忽略。

**Comment by Snapmali** [comment]
可以再详细描述一下问题吗？是断连后等待一段时间又会出现下一个断连提醒，且在discord中发送消息时脚本无反应，还是断连之后卡在disconnect再毫无动态。
若断连后在discord中发送消息时脚本有反应，则是由于未知原因脚本未捕获connect事件，对脚本运行无影响。

如果方便的话，希望能提供包含异常断连日志的discord_monitor.log文件及discord.py输出的详细log信息。其中详细log信息获取方式如下：

在脚本第19行后加入
```
import logging

logger = logging.getLogger('discord')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)
```
脚本运行后，生成的discord.log文件即为详细log信息。注意对文件中的隐私数据进行脱敏处理。

**Comment by xiaobaozi233** [comment]
[WARN][2020/08/07 12:55:54][Discord] Disconnected...
[WARN][2020/08/07 15:35:27][Discord] Disconnected...
[WARN][2020/08/07 17:34:44][Discord] Disconnected...
[WARN][2020/08/07 19:09:03][Discord] Disconnected...
[INFO][2020/08/07 19:27:24][Discord][发送消息] ID:



海外服务器好像没有这个问题了，国内服务器通过代理，到第三次断连提示后就无法收到任何消息了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snapmali/discord-monitor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 晚上9:36
收件人:&nbsp;"Snapmali/discord-monitor"<discord-monitor@noreply.github.com&gt;;
抄送:&nbsp;"xiaobaozi"<xiaobaozi@miku.tw&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Snapmali/discord-monitor] 掉线无法自动重连的问题 (#4)





 
可以再详细描述一下问题吗？是断连后等待一段时间又会出现下一个断连提醒，且在discord中发送消息时脚本无反应，还是断连之后卡在disconnect再毫无动态。
 若断连后在discord中发送消息时脚本有反应，则是由于未知原因脚本未捕获connect事件，对脚本运行无影响。
 
如果方便的话，希望能提供包含异常断连日志的discord_monitor.log文件及discord.py输出的详细log信息。其中详细log信息获取方式如下：
 
在脚本第19行后加入
 import logging logger = logging.getLogger('discord') logger.setLevel(logging.DEBUG) handler = logging.FileHandler(filename='discord.log', encoding='utf-8', mode='w') handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s')) logger.addHandler(handler)  
脚本运行后，生成的discord.log文件即为详细log信息。注意对文件中的隐私数据进行脱敏处理。

**Comment by Snapmali** [comment]
那可能确实是代理支持的问题，我这边应该没法解决……
如果在大陆使用的话可以尝试按照上面说的在Windows端使用proxifier、或在Linux端使用netns，以避免在直接脚本中使用代理。

另外由于酷Q停运，若仍在使用脚本推送至QQ的功能，建议不要关闭酷Q客户端。

**Comment by Snapmali** [comment]
discord.py库在1.4.1版本后由websocket迁移至aiohttp依赖库。我这边更新后经过几天的测试，掉线后无法重连的问题未再次发生。
建议使用`pip install -U discord.py`命令更新discord.py库，或下载使用本脚本最新版本release。

若问题仍未解决请reopen该issue。
