### ISSUE TITLE
请问有没有办法转发指定名称的频道信息

### ISSUE THREAD

**Issue by xiaobaozi233** [Snapmali/discord-monitor#5]
不知道老外的discord做了什么操作，频道名称没有变化但id每天都在变化。于是现在每天都要上去更新一下频道id。
请问能不能增加转发某个指定名称频道的信息，而跳过频道id？谢谢！

**Comment by Snapmali** [comment]
最新的commit和release已经实现了这个功能，注意config文件规则更新
如果有bug请反馈

这频道ID每天都变是个什么操作……

**Comment by xiaobaozi233** [comment]
感谢！测试暂时没问题！

EVE这个游戏老外的discord发集结通知。应该是为了防止间谍还是什么的，每次都是一个新的频道，但是名字一样。

**Comment by xiaobaozi233** [comment]
刚看了一下好像每次更新频道后的第一条信息接收不到。这个有办法解决吗？

**Comment by Snapmali** [comment]
这个问题实际上是在轮询间隔时修改频道id并发布信息导致的，由于信息发布时脚本还未更新频道id列表，所以没能推送信息。
推荐更新脚本，新的版本已经通过改变监听机制解决了这个问题，如果有bug请反馈。
也可通过在config.json中减小“interval”值以降低轮询间隔解决。

**Comment by xiaobaozi233** [comment]
感谢，我再观察一段时间
