### ISSUE TITLE
可不可以把抓到的信息转发到其他的discord频道

### ISSUE THREAD

**Issue by Whitezzz41** [Snapmali/discord-monitor#6]
可不可以把抓到的信息转发到其他的discord频道

**Comment by Snapmali** [comment]
目前并没有这样的打算，我想实现的功能还是把discord消息往qq转发

**Comment by 1771269478** [comment]
请问加钱可以实现这个功能吗

**Comment by ferrenlove** [comment]
有discord转发去其他discord频道的 python 包，网上搜或者fiverr，我搞了一个，但是不知道最近老自动停止有error msg，debug了很久都不行

**Comment by 1771269478** [comment]
啊? 你是谁




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 下午4:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snapmali/discord-monitor] 可不可以把抓到的信息转发到其他的discord频道 (#6)





 
有discord转发去其他discord频道的 python 包，网上搜或者fiverr，我搞了一个，但是不知道最近老自动停止有error msg，debug了很久都不行

**Comment by ferrenlove** [comment]
我是搞了这个discord to discord 小程序但是老有bug想着替代方案，最后找到这里来的人，还在学习ing。不知道怎么设置，只能把历史文件一个个看过来

**Comment by 1771269478** [comment]
你是不是不认识我
我花 1000usd ..委托github.com 上的人做了一个
可以转发&nbsp;discord to discord,,也可以discord to QQ






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snapmali/discord-monitor] 可不可以把抓到的信息转发到其他的discord频道 (#6)





 
我是搞了这个discord to discord 小程序但是老有bug想着替代方案，最后找到这里来的人，还在学习ing。不知道怎么设置，只能把历史文件一个个看过来

**Comment by 1771269478** [comment]
这个作者不是写出来这个程序了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snapmali/discord-monitor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snapmali/discord-monitor] 可不可以把抓到的信息转发到其他的discord频道 (#6)





 
我是搞了这个discord to discord 小程序但是老有bug想着替代方案，最后找到这里来的人，还在学习ing。不知道怎么设置，只能把历史文件一个个看过来

**Comment by ferrenlove** [comment]
我没看到作者实现了discord to discord啊，这个博主不是一直做的是discord to
qq吗？？？ 有discord to discord求链接

**Comment by 1771269478** [comment]
我就是问这个作者买的....你直接问他就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snapmali/discord-monitor] 可不可以把抓到的信息转发到其他的discord频道 (#6)





 
我没看到作者实现了discord to discord啊，这个博主不是一直做的是discord to
 qq吗？？？ 有discord to discord求链接

**Comment by ferrenlove** [comment]
作者我也想拥有 discord to discord或者 discord to qq or wechat，求联系方式，如何联系啊。可以留email吗？ ferrennetwork@gmail.com 谢谢亲爱的作者，和楼上帅哥好心人. 我的威兴号。 7.6.5.7.6.1.0
