### ISSUE TITLE
通过频道名称监听项留空时脚本接收消息报错TypeError

### ISSUE THREAD

**Issue by LaoFang1s** [Snapmali/discord-monitor#7]
你好，log如下，按照wiki配置了。

Fetch ID xxxxx's username failed.
Ignoring exception in on_guild_channel_pins_update
Traceback (most recent call last):
  File "site-packages\discord\client.py", line 333, in _run_event
  File "DiscordMonitor.py", line 369, in on_guild_channel_pins_update
TypeError: argument of type 'NoneType' is not iterable
Ignoring exception in on_guild_channel_pins_update

**Comment by Snapmali** [comment]
设置文件中频道名称留空时脚本接收消息会报错，是上个版本更新后新出的bug，重看了遍代码发现这挺弱智一错误

最新的commit和release修复了此问题，建议更新脚本，如有bug请反馈

**Comment by LaoFang1s** [comment]
exe运行后登录 然后就没下文了。go-cqhttp 正常运行。
Logging in...
Logged in as xxxxxxx#xxxx, ID: xxxxxxxxxxxxxxx.
[INFO][2021/01/28 18:19:21][Discord] Logged in as xxxxx#xxxx, ID: xxxxxxxxxxxxxx.

**Comment by Snapmali** [comment]
我这边运行正常，可能是config.json文件没有正确配置，建议按照readme重新比对格式，或将你的配置文件脱敏后贴在这里

**Comment by LaoFang1s** [comment]
先感谢答复！应该是我配置问题，monitor配置全空的时候是有反应的 可以监听转发全部消息。
    "monitor": {
        "user_id": {},
        "channel": [],
        "channel_name": [],
        "server": []
    },
如图，比如我想监听这个itools 下的 general-chat 这个频道内的所有消息
假设为他们的id为id1、id2 我应该怎么正确填写到上面这段？可能我对server和channel没搞清楚
![dis](https://user-images.githubusercontent.com/44582189/106172378-b9e64d00-61cd-11eb-8043-ace5bd7499ae.png)

如果按名称监听是这么填写么：
        "user_id": {},
        "channel": [],
        "channel_name": [["itools", "general-chat"]],
        "server": []

**Comment by Snapmali** [comment]
按照名称监听确实是这么填
按照id监听是
"user_id": {},
"channel": [id2],
"channel_name": [],
"server": []

**Comment by LaoFang1s** [comment]
那难道是我id复制不对？各种填法我都试过，没有反应，全空的时候有反应。

**Comment by LaoFang1s** [comment]
> 按照名称监听的确实是这么填
> 按照id监听是
> “ user_id”：{}，
> “ channel”：[id2]，
> “ channel_name”：[]，
> “ server”：[]

**Comment by LaoFang1s** [comment]
感谢大佬 升级版本后已解决。
