### ISSUE TITLE
转发附件相关

### ISSUE THREAD

**Issue by RaymondW722** [Snapmali/discord-monitor#9]
discord频道发送图片/档案的消息时会以链接的形式转发至QQ
能不能弄成发送图片及上传档案

**Comment by Snapmali** [comment]
图片应该是可以搞的，其他附件可能是没有办法了
稍晚点我实现一下试试

**Comment by Snapmali** [comment]
新版本已实现在QQ消息内部显示图片，更新后如有bug请反馈
